In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("cleaned_college_faq.csv")

df.head()

,ID,Category,Question,Answer,Answer_Length
0,1,Greeting,hi,Hello! Welcome to the College Query Chatbot.,44
1,2,Greeting,hello,Hi! How can I help you today?,29
2,3,Greeting,good morning,Good Morning! Welcome to our college.,37
3,4,Greeting,good evening,Good Evening! How can I assist you?,35
4,5,Greeting,bye,Thank you! Have a nice day.,27

In [3]:
print("Number of questions:", len(df))
print("Columns:", df.columns.tolist())

Number of questions: 101
Columns: ['ID', 'Category', 'Question', 'Answer', 'Answer_Length']

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             101 non-null    int64
 1   Category       101 non-null    object
 2   Question       101 non-null    object
 3   Answer         101 non-null    object
 4   Answer_Length  101 non-null    int64
dtypes: int64(2), object(3)
memory usage: 4.1+ KB

In [5]:
def preprocess_text(text):
    text = str(text)
    text = text.lower()
    text = text.strip()
    return text

In [6]:
df["Question"] = df["Question"].apply(preprocess_text)

df.head()

,ID,Category,Question,Answer,Answer_Length
0,1,Greeting,hi,Hello! Welcome to the College Query Chatbot.,44
1,2,Greeting,hello,Hi! How can I help you today?,29
2,3,Greeting,good morning,Good Morning! Welcome to our college.,37
3,4,Greeting,good evening,Good Evening! How can I assist you?,35
4,5,Greeting,bye,Thank you! Have a nice day.,27

In [7]:
def chatbot(user_question):

    user_question = preprocess_text(user_question)

    for index, question in enumerate(df["Question"]):

        if user_question == question:
            return df.iloc[index]["Answer"]

    return "Sorry, I couldn't understand your question. Please try again."

In [8]:
print(chatbot("hi"))

Hello! Welcome to the College Query Chatbot.

In [9]:
print(chatbot("library"))

The library is open from 9 AM to 5 PM.

In [10]:
print(chatbot("hostel"))

Hostel facilities are available for boys and girls.

In [11]:
print(chatbot("placements"))

Our Placement Cell conducts training and campus drives.

In [12]:
def chatbot(user_question):

    user_question = preprocess_text(user_question)

    # Exact matching
    for index, question in enumerate(df["Question"]):
        if user_question == question:
            return df.iloc[index]["Answer"]

    # Keyword matching
    keywords = {
        "library": "Library",
        "hostel": "Hostel",
        "admission": "Admission",
        "course": "Courses",
        "courses": "Courses",
        "placement": "Placement",
        "placements": "Placement",
        "fee": "Fees",
        "fees": "Fees",
        "exam": "Examination",
        "exams": "Examination"
    }

    for word, category in keywords.items():

        if word in user_question:

            category_data = df[
                df["Category"].str.lower() == category.lower()
            ]

            if not category_data.empty:
                return category_data.iloc[0]["Answer"]

    return "Sorry, I couldn't understand your question. Please try again."

In [13]:
print(chatbot("tell me about the library"))

The library is open from 9 AM to 5 PM.

In [14]:
print(chatbot("what are the hostel facilities"))

Hostel facilities are available for boys and girls.

In [15]:
print(chatbot("how can I get admission"))

Please visit the Admission Office or apply online.

In [16]:
print(chatbot("tell me about placements"))

Our Placement Cell conducts training and campus drives.

In [17]:
print(chatbot("what is the fee structure"))

Please contact the Accounts Office for fee details.

In [18]:
print("========================================")
print("       COLLEGE QUERY CHATBOT")
print("========================================")
print("Ask me about admissions, courses, library,")
print("hostel, placements, fees, and examinations.")
print("Type 'bye' to exit.")
print("========================================")

while True:

    user_question = input("You: ")

    if user_question.lower().strip() == "bye":
        print("Bot: Thank you! Have a nice day.")
        break

    answer = chatbot(user_question)

    print("Bot:", answer)

========================================
       COLLEGE QUERY CHATBOT
========================================
Ask me about admissions, courses, library,
hostel, placements, fees, and examinations.
Type 'bye' to exit.
========================================
Bot: Sorry, I couldn't understand your question. Please try again.
Bot: Sorry, I couldn't understand your question. Please try again.
Bot: Hello! Welcome to the College Query Chatbot.
Bot: Hello! Welcome to the College Query Chatbot.
Bot: Hello! Welcome to the College Query Chatbot.
Bot: The library is open from 9 AM to 5 PM.
Bot: Thank you! Have a nice day.

In [20]:
print(chatbot("what is the weather today"))

Sorry, I couldn't understand your question. Please try again.

In [22]:
test_df = pd.read_csv("test_questions.csv")

test_df.head()

   ID  Category        Question                                        Answer
0   1  Greeting              hi  Hello! Welcome to the College Query Chatbot.
1   2  Greeting           hello                 Hi! How can I help you today?
2   3  Greeting             hey                  Hello! How can I assist you?
3   4  Greeting    good morning         Good Morning! Welcome to our college.
4   5  Greeting  good afternoon           Good Afternoon! How can I help you?

In [24]:
results = []

for question in test_df["Question"]:
    answer = chatbot(question)
    results.append(answer)

test_df["Chatbot_Answer"] = results

test_df.head(100)

,ID,Category,Question,Answer,Chatbot_Answer
0,1,Greeting,hi,Hello! Welcome to the College Query Chatbot.,Hello! Welcome to the College Query Chatbot.
1,2,Greeting,hello,Hi! How can I help you today?,Hi! How can I help you today?
2,3,Greeting,hey,Hello! How can I assist you?,"Sorry, I couldn't understand your question. Pl..."
3,4,Greeting,good morning,Good Morning! Welcome to our college.,Good Morning! Welcome to our college.
4,5,Greeting,good afternoon,Good Afternoon! How can I help you?,"Sorry, I couldn't understand your question. Pl..."
...,...,...,...,...,...
95,96,General,college timings,College working hours are generally according ...,College working hours are from 9:00 AM to 4:30...
96,97,General,college location,Please check the official college information ...,"Sorry, I couldn't understand your question. Pl..."
97,98,General,student activities,The college conducts various academic cultural...,"Sorry, I couldn't understand your question. Pl..."
98,99,General,sports facilities,The college provides sports facilities for stu...,"Sorry, I couldn't understand your question. Pl..."
99,100,General,contact college,Please contact the college office or reception...,"Sorry, I couldn't understand your question. Pl..."

In [25]:
test_df["Correct"] = (
    test_df["Answer"].str.strip().str.lower()
    == test_df["Chatbot_Answer"].str.strip().str.lower()
)

accuracy = test_df["Correct"].mean() * 100

print("Chatbot Accuracy:", round(accuracy, 2), "%")

Chatbot Accuracy: 11.0 %

In [26]:
test_df.to_csv("test_results.csv", index=False)

print("Test results saved successfully!")

Test results saved successfully!

In [27]:
print("FAQ questions:", len(df))
print("Test questions:", len(test_df))

print("\nCategories in FAQ:")
print(df["Category"].value_counts())

FAQ questions: 101
Test questions: 100

Categories in FAQ:
Category
Library        13
Admission      11
Greeting       10
Placement      10
Faculty        10
Fees           10
Examination    10
Courses         9
Hostel          9
Campus          9
Name: count, dtype: int64

In [29]:
df.head(100)

,ID,Category,Question,Answer,Answer_Length
0,1,Greeting,hi,Hello! Welcome to the College Query Chatbot.,44
1,2,Greeting,hello,Hi! How can I help you today?,29
2,3,Greeting,good morning,Good Morning! Welcome to our college.,37
3,4,Greeting,good evening,Good Evening! How can I assist you?,35
4,5,Greeting,bye,Thank you! Have a nice day.,27
...,...,...,...,...,...
95,100,Campus,college timings,College working hours are from 9:00 AM to 4:30...,50
96,101,Library,where is library,The library is located in Block A.,34
97,102,Library,library location,The library is located in Block A.,34
98,103,Library,how to reach library,The library is located in Block A.,34
99,104,Admission,how can i get admission,Please visit the Admission Office or apply onl...,50

In [30]:
df["Question"].tolist()

['hi',
 'hello',
 'good morning',
 'good evening',
 'bye',
 'how are you',
 'who are you',
 'thank you',
 'thanks',
 'good night',
 'admission',
 'admission process',
 'eligibility',
 'application form',
 'admission fee',
 'last date for admission',
 'management quota',
 'lateral entry',
 'scholarship',
 'branches',
 'computer science',
 'information technology',
 'artificial intelligence',
 'civil engineering',
 'mechanical engineering',
 'electronics',
 'electrical engineering',
 'duration of course',
 'library',
 'library timing',
 'library books',
 'digital library',
 'library card',
 'book issue',
 'book return',
 'newspapers',
 'reference books',
 'library rules',
 'hostel',
 'hostel fee',
 'hostel rooms',
 'mess',
 'hostel timing',
 'hostel warden',
 'room allocation',
 'hostel rules',
 'leave permission',
 'placements',
 'placement cell',
 'companies',
 'highest package',
 'average package',
 'internship',
 'training',
 'mock interview',
 'resume building',
 'placement eligibility',
 'fee structure',
 'pay fees',
 'online payment',
 'fee receipt',
 'refund policy',
 'late fee',
 'tuition fee',
 'hostel fee',
 'bus fee',
 'scholarship amount',
 'faculty',
 'hod',
 'principal',
 'staff',
 'mentor',
 'office hours',
 'email faculty',
 'department office',
 'faculty room',
 'contact faculty',
 'exam timetable',
 'exam',
 'results',
 'internal marks',
 'backlogs',
 'exam hall',
 'hall ticket',
 'revaluation',
 'supplementary exams',
 'attendance for exams',
 'wifi',
 'bus facility',
 'sports',
 'gym',
 'medical facility',
 'student clubs',
 'nss',
 'ncc',
 'college timings',
 'where is library',
 'library location',
 'how to reach library',
 'how can i get admission',
 'how to join college']

In [31]:
test_cases = [
    "hi",
    "tell me about the library",
    "what are the hostel facilities",
    "how can I get admission",
    "what courses are available",
    "tell me about placements",
    "what are the college fees",
    "when are the exams",
    "how can I check attendance",
    "is there a bus facility"
]

for question in test_cases:
    print("You:", question)
    print("Bot:", chatbot(question))
    print("-" * 60)

You: hi
Bot: Hello! Welcome to the College Query Chatbot.
------------------------------------------------------------
You: tell me about the library
Bot: The library is open from 9 AM to 5 PM.
------------------------------------------------------------
You: what are the hostel facilities
Bot: Hostel facilities are available for boys and girls.
------------------------------------------------------------
You: how can I get admission
Bot: Please visit the Admission Office or apply online.
------------------------------------------------------------
You: what courses are available
Bot: Our college offers multiple engineering branches.
------------------------------------------------------------
You: tell me about placements
Bot: Our Placement Cell conducts training and campus drives.
------------------------------------------------------------
You: what are the college fees
Bot: Please contact the Accounts Office for fee details.
------------------------------------------------------------
You: when are the exams
Bot: Exam schedules are published on the student portal.
------------------------------------------------------------
You: how can I check attendance
Bot: Sorry, I couldn't understand your question. Please try again.
------------------------------------------------------------
You: is there a bus facility
Bot: Sorry, I couldn't understand your question. Please try again.
------------------------------------------------------------

In [32]:
test_df["Correct"] = (
    test_df["Answer"].str.strip().str.lower()
    == test_df["Chatbot_Answer"].str.strip().str.lower()
)

accuracy = test_df["Correct"].mean() * 100

print("Chatbot Accuracy:", round(accuracy, 2), "%")

Chatbot Accuracy: 11.0 %

In [33]:
df[["Category", "Question", "Answer"]].head(20)

,Category,Question,Answer
0,Greeting,hi,Hello! Welcome to the College Query Chatbot.
1,Greeting,hello,Hi! How can I help you today?
2,Greeting,good morning,Good Morning! Welcome to our college.
3,Greeting,good evening,Good Evening! How can I assist you?
4,Greeting,bye,Thank you! Have a nice day.
5,Greeting,how are you,I am doing great! How can I help you?
6,Greeting,who are you,I am the College Query Chatbot.
7,Greeting,thank you,You're welcome! Happy to help.
8,Greeting,thanks,You're welcome.
9,Greeting,good night,Good Night! Take care.
10,Admission,admission,Please visit the Admission Office for admissio...
11,Admission,admission process,You can apply online or visit the Admission Of...
12,Admission,eligibility,Please check the eligibility criteria on the c...
13,Admission,application form,Application forms are available on the college...
14,Admission,admission fee,Please contact the Accounts Office for fee det...
15,Admission,last date for admission,Please check the academic calendar for admissi...
16,Admission,management quota,Please contact the Admission Office for manage...
17,Admission,lateral entry,Lateral entry admissions are available for eli...
18,Admission,scholarship,Scholarships are available for eligible students.
19,Courses,branches,Our college offers multiple engineering branches.

In [34]:
test_df[["Category", "Question", "Answer"]].head(20)

,Category,Question,Answer
0,Greeting,hi,Hello! Welcome to the College Query Chatbot.
1,Greeting,hello,Hi! How can I help you today?
2,Greeting,hey,Hello! How can I assist you?
3,Greeting,good morning,Good Morning! Welcome to our college.
4,Greeting,good afternoon,Good Afternoon! How can I help you?
5,Greeting,good evening,Good Evening! How can I assist you?
6,Greeting,how are you,I am doing great! How can I help you?
7,Greeting,what can you do,I can answer common questions about the college.
8,Greeting,who are you,I am the College Query Chatbot.
9,Greeting,bye,Thank you! Have a nice day.
10,Admission,admission,Please visit the Admission Office for admissio...
11,Admission,how can I get admission,Please contact the Admission Office for the ad...
12,Admission,admission process,The admission process depends on the course an...
13,Admission,admission details,Please visit the college admission section for...
14,Admission,what are the eligibility criteria,Eligibility criteria vary according to the cou...
15,Admission,documents required for admission,Please contact the Admission Office for the li...
16,Admission,when does admission start,Admission dates are announced by the college o...
17,Admission,how to apply for admission,You can apply through the official college adm...
18,Admission,admission office,The Admission Office helps students with admis...
19,Admission,can I get admission information,Yes! Please contact the Admission Office for d...

In [36]:
def predict_category(question):

    question = preprocess_text(question)

    category_keywords = {
        "library": "Library",
        "book": "Library",
        "books": "Library",

        "admission": "Admission",
        "apply": "Admission",
        "eligibility": "Admission",

        "course": "Courses",
        "courses": "Courses",
        "branch": "Courses",
        "branches": "Courses",

        "placement": "Placement",
        "placements": "Placement",
        "job": "Placement",
        "jobs": "Placement",

        "fee": "Fees",
        "fees": "Fees",
        "payment": "Fees",
        "scholarship": "Fees",

        "exam": "Examination",
        "exams": "Examination",
        "examination": "Examination",
        "hall ticket": "Examination",

        "hostel": "Hostel",
        "room": "Hostel",
        "rooms": "Hostel",

        "faculty": "Faculty",
        "teacher": "Faculty",
        "teachers": "Faculty",

        "campus": "Campus",

        "hi": "Greeting",
        "hello": "Greeting",
        "hey": "Greeting",

        "attendance": "Campus"
    }

    for keyword, category in category_keywords.items():
        if keyword in question:
            return category

    return "Unknown"

In [37]:
test_df["Predicted_Category"] = test_df["Question"].apply(predict_category)

test_df[[
    "Question",
    "Category",
    "Predicted_Category"
]].head(20)

                             Question   Category Predicted_Category
0                                  hi   Greeting           Greeting
1                               hello   Greeting           Greeting
2                                 hey   Greeting           Greeting
3                        good morning   Greeting            Unknown
4                      good afternoon   Greeting            Unknown
5                        good evening   Greeting            Unknown
6                         how are you   Greeting            Unknown
7                     what can you do   Greeting            Unknown
8                         who are you   Greeting            Unknown
9                                 bye   Greeting            Unknown
10                          admission  Admission          Admission
11            how can I get admission  Admission          Admission
12                  admission process  Admission          Admission
13                  admission details  Admission          Admission
14  what are the eligibility criteria  Admission          Admission
15   documents required for admission  Admission          Admission
16          when does admission start  Admission          Admission
17         how to apply for admission  Admission          Admission
18                   admission office  Admission          Admission
19    can I get admission information  Admission          Admission

In [38]:
test_df["Correct"] = (
    test_df["Category"].str.strip().str.lower()
    ==
    test_df["Predicted_Category"].str.strip().str.lower()
)

accuracy = test_df["Correct"].mean() * 100

print("Category Classification Accuracy:",
      round(accuracy, 2), "%")

Category Classification Accuracy: 69.0 %

In [39]:
wrong = test_df[test_df["Correct"] == False]

print("Wrong predictions:", len(wrong))

wrong[[
    "Question",
    "Category",
    "Predicted_Category"
]]

Wrong predictions: 31

                    Question     Category Predicted_Category
3               good morning     Greeting            Unknown
4             good afternoon     Greeting            Unknown
5               good evening     Greeting            Unknown
6                how are you     Greeting            Unknown
7            what can you do     Greeting            Unknown
8                who are you     Greeting            Unknown
9                        bye     Greeting            Unknown
23                       cse      Courses            Unknown
28         civil engineering      Courses            Unknown
29    mechanical engineering      Courses            Unknown
47          hostel admission       Hostel          Admission
48                hostel fee       Hostel               Fees
55     placement eligibility    Placement          Admission
58  internship opportunities    Placement           Greeting
77                    result  Examination            Unknown
80                attendance   Attendance             Campus
81     attendance percentage   Attendance             Campus
82        minimum attendance   Attendance             Campus
83       attendance shortage   Attendance             Campus
84   how to check attendance   Attendance             Campus
87                       hod      Faculty            Unknown
90                 transport    Transport            Unknown
91              bus facility    Transport            Unknown
92               bus timings    Transport            Unknown
93          transport routes    Transport            Unknown
94                  bus pass    Transport            Unknown
95           college timings      General            Unknown
96          college location      General            Unknown
97        student activities      General            Unknown
98         sports facilities      General            Unknown
99           contact college      General            Unknown

In [40]:
print(pd.crosstab(
    test_df["Category"],
    test_df["Predicted_Category"]
))

Predicted_Category  Admission  Campus  Courses  Examination  Faculty  Fees  \
Category
Admission                  10       0        0            0        0     0
Attendance                  0       5        0            0        0     0
Courses                     0       0        7            0        0     0
Examination                 0       0        0            9        0     0
Faculty                     0       0        0            0        4     0
Fees                        0       0        0            0        0    10
General                     0       0        0            0        0     0
Greeting                    0       0        0            0        0     0
Hostel                      1       0        0            0        0     1
Library                     0       0        0            0        0     0
Placement                   1       0        0            0        0     0
Transport                   0       0        0            0        0     0

Predicted_Category  Greeting  Hostel  Library  Placement  Unknown
Category
Admission                  0       0        0          0        0
Attendance                 0       0        0          0        0
Courses                    0       0        0          0        3
Examination                0       0        0          0        1
Faculty                    0       0        0          0        1
Fees                       0       0        0          0        0
General                    0       0        0          0        5
Greeting                   3       0        0          0        7
Hostel                     0       8        0          0        0
Library                    0       0       10          0        0
Placement                  1       0        0          8        0
Transport                  0       0        0          0        5

In [42]:
wrong = test_df[test_df["Correct"] == False]

print("Wrong predictions:", len(wrong))

wrong[[
    "Question",
    "Category",
    "Predicted_Category"
]]

Wrong predictions: 31

                    Question     Category Predicted_Category
3               good morning     Greeting            Unknown
4             good afternoon     Greeting            Unknown
5               good evening     Greeting            Unknown
6                how are you     Greeting            Unknown
7            what can you do     Greeting            Unknown
8                who are you     Greeting            Unknown
9                        bye     Greeting            Unknown
23                       cse      Courses            Unknown
28         civil engineering      Courses            Unknown
29    mechanical engineering      Courses            Unknown
47          hostel admission       Hostel          Admission
48                hostel fee       Hostel               Fees
55     placement eligibility    Placement          Admission
58  internship opportunities    Placement           Greeting
77                    result  Examination            Unknown
80                attendance   Attendance             Campus
81     attendance percentage   Attendance             Campus
82        minimum attendance   Attendance             Campus
83       attendance shortage   Attendance             Campus
84   how to check attendance   Attendance             Campus
87                       hod      Faculty            Unknown
90                 transport    Transport            Unknown
91              bus facility    Transport            Unknown
92               bus timings    Transport            Unknown
93          transport routes    Transport            Unknown
94                  bus pass    Transport            Unknown
95           college timings      General            Unknown
96          college location      General            Unknown
97        student activities      General            Unknown
98         sports facilities      General            Unknown
99           contact college      General            Unknown

In [44]:
test_df.to_csv("test_results.csv", index=False)

print("Test results saved successfully!")

Test results saved successfully!

In [2]:
import pandas as pd

# Load FAQ dataset
df = pd.read_csv("cleaned_college_faq.csv")


# Preprocess text
def preprocess_text(text):
    return str(text).lower().strip()


df["Question"] = df["Question"].apply(preprocess_text)


# Rule-based chatbot
def chatbot(user_question):

    user_question = preprocess_text(user_question)

    # Exact matching
    for index, question in enumerate(df["Question"]):
        if user_question == question:
            return df.iloc[index]["Answer"]

    # Keyword rules
    keywords = {
        "library": "Library",
        "book": "Library",
        "books": "Library",

        "admission": "Admission",
        "apply": "Admission",
        "eligibility": "Admission",

        "course": "Courses",
        "courses": "Courses",
        "branch": "Courses",

        "placement": "Placement",
        "placements": "Placement",
        "job": "Placement",

        "fee": "Fees",
        "fees": "Fees",
        "scholarship": "Fees",

        "exam": "Examination",
        "exams": "Examination",
        "examination": "Examination",

        "hostel": "Hostel",
        "room": "Hostel",
        "rooms": "Hostel",

        "faculty": "Faculty",
        "teacher": "Faculty",
        "teachers": "Faculty",

        "campus": "Campus",

        "hi": "Greeting",
        "hello": "Greeting",
        "hey": "Greeting"
    }

    for keyword, category in keywords.items():

        if keyword in user_question:

            category_data = df[
                df["Category"].str.lower() == category.lower()
            ]

            if not category_data.empty:
                return category_data.iloc[0]["Answer"]

    return "Sorry, I couldn't understand your question."


# Start chatbot
print("====================================")
print("       COLLEGE QUERY CHATBOT")
print("====================================")
print("Type 'bye' to exit.")

while True:

    user_question = input("You: ")

    if user_question.lower().strip() == "bye":
        print("Bot: Thank you! Have a nice day.")
        break

    print("Bot:", chatbot(user_question))

====================================
       COLLEGE QUERY CHATBOT
====================================
Type 'bye' to exit.
Bot: The library is open from 9 AM to 5 PM.
Bot: Our Placement Cell conducts training and campus drives.
Bot: Sorry, I couldn't understand your question.
Bot: Hello! Welcome to the College Query Chatbot.
Bot: Our college has experienced faculty members.
Bot: Please contact the Accounts Office for fee details.
Bot: Thank you! Have a nice day.