In [1]:
import pandas as pd

In [ ]:
df.head()

   ID  Category      Question                                        Answer
0   1  Greeting            hi  Hello! Welcome to the College Query Chatbot.
1   2  Greeting         hello                 Hi! How can I help you today?
2   3  Greeting  good morning         Good Morning! Welcome to our college.
3   4  Greeting  good evening           Good Evening! How can I assist you?
4   5  Greeting           bye                   Thank you! Have a nice day.

In [ ]:
df.tail()

,ID,Category,Question,Answer
5,6,Admission,admission,Please visit the Admission Office for admissio...
6,7,Courses,courses,We offer CSE IT ECE EEE AIML Civil and Mechani...
7,8,Library,library,The library is open from 9 AM to 5 PM.
8,9,Hostel,hostel,Hostel facilities are available for both boys ...
9,10,Placement,placements,Our Placement Cell conducts training and campu...

In [ ]:
df.shape

(10, 4)

In [ ]:
df.columns

Index(['ID', 'Category', 'Question', 'Answer'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        10 non-null     int64
 1   Category  10 non-null     object
 2   Question  10 non-null     object
 3   Answer    10 non-null     object
dtypes: int64(1), object(3)
memory usage: 452.0+ bytes

In [ ]:
df.describe(include="all")

,ID,Category,Question,Answer
count,10.00000,10,10,10
unique,NaN,6,10,10
top,NaN,Greeting,hi,Hello! Welcome to the College Query Chatbot.
freq,NaN,5,1,1
mean,5.50000,NaN,NaN,NaN
std,3.02765,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN
25%,3.25000,NaN,NaN,NaN
50%,5.50000,NaN,NaN,NaN
75%,7.75000,NaN,NaN,NaN
max,10.00000,NaN,NaN,NaN

In [ ]:
df.isnull().sum()

ID          0
Category    0
Question    0
Answer      0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Category"].unique()

array(['Greeting', 'Admission', 'Courses', 'Library', 'Hostel',
       'Placement'], dtype=object)

In [ ]:
df["Category"].value_counts()

Category
Greeting     5
Admission    1
Courses      1
Library      1
Hostel       1
Placement    1
Name: count, dtype: int64

In [ ]:
df["Question"] = df["Question"].str.lower()

In [ ]:
df.to_csv("../cleaned_dataset/cleaned_college_faq.csv", index=False)

In [ ]:
cleaned_df = pd.read_csv("../cleaned_dataset/cleaned_college_faq.csv")
cleaned_df.head()

   ID  Category      Question                                        Answer
0   1  Greeting            hi  Hello! Welcome to the College Query Chatbot.
1   2  Greeting         hello                 Hi! How can I help you today?
2   3  Greeting  good morning         Good Morning! Welcome to our college.
3   4  Greeting  good evening           Good Evening! How can I assist you?
4   5  Greeting           bye                   Thank you! Have a nice day.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("../dataset/college_faq.csv", sep=";")

In [ ]:
df.head()

                         ID,Category,Question,Answer
0  1,Greeting,hi,Hello! Welcome to the College Qu...
1     2,Greeting,hello,Hi! How can I help you today?
2  3,Greeting,good morning,Good Morning! Welcome ...
3  4,Greeting,good evening,Good Evening! How can ...
4         5,Greeting,bye,Thank you! Have a nice day.

In [3]:
import pandas as pd

df = pd.read_csv(
    "../dataset/college_faq.csv",
    on_bad_lines="skip"
)

print(df.shape)

(101, 4)

In [4]:
import pandas as pd

df = pd.read_csv("../dataset/college_faq.csv", on_bad_lines="skip")

print(df.shape)
print(df.head())

(101, 4)
   ID  Category      Question                                        Answer
0   1  Greeting            hi  Hello! Welcome to the College Query Chatbot.
1   2  Greeting         hello                 Hi! How can I help you today?
2   3  Greeting  good morning         Good Morning! Welcome to our college.
3   4  Greeting  good evening           Good Evening! How can I assist you?
4   5  Greeting           bye                   Thank you! Have a nice day.

In [5]:
print(df.isnull().sum())

ID          0
Category    0
Question    0
Answer      0
dtype: int64

In [6]:
print(df.duplicated().sum())

0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        101 non-null    int64
 1   Category  101 non-null    object
 2   Question  101 non-null    object
 3   Answer    101 non-null    object
dtypes: int64(1), object(3)
memory usage: 3.3+ KB

In [8]:
print(df["Category"].value_counts())

Category
Library        13
Admission      11
Greeting       10
Placement      10
Faculty        10
Fees           10
Examination    10
Courses         9
Hostel          9
Campus          9
Name: count, dtype: int64

In [9]:
df.to_csv("../cleaned_dataset/cleaned_college_faq.csv", index=False)
print("Dataset saved successfully!")

Dataset saved successfully!

In [12]:
df.head(10)

   ID  Category      Question                                        Answer
0   1  Greeting            hi  Hello! Welcome to the College Query Chatbot.
1   2  Greeting         hello                 Hi! How can I help you today?
2   3  Greeting  good morning         Good Morning! Welcome to our college.
3   4  Greeting  good evening           Good Evening! How can I assist you?
4   5  Greeting           bye                   Thank you! Have a nice day.
5   6  Greeting   how are you         I am doing great! How can I help you?
6   7  Greeting   who are you               I am the College Query Chatbot.
7   8  Greeting     thank you                You're welcome! Happy to help.
8   9  Greeting        thanks                               You're welcome.
9  10  Greeting    good night                        Good Night! Take care.

In [13]:
df.tail(10)

,ID,Category,Question,Answer
91,96,Campus,medical facility,First aid and medical assistance are available.
92,97,Campus,student clubs,Various technical and cultural clubs are active.
93,98,Campus,NSS,NSS activities are conducted regularly.
94,99,Campus,NCC,NCC unit is available for eligible students.
95,100,Campus,college timings,College working hours are from 9:00 AM to 4:30...
96,101,Library,where is library,The library is located in Block A.
97,102,Library,library location,The library is located in Block A.
98,103,Library,how to reach library,The library is located in Block A.
99,104,Admission,how can i get admission,Please visit the Admission Office or apply onl...
100,105,Admission,how to join college,Please visit the Admission Office or apply onl...

In [14]:
print("Rows and Columns:", df.shape)

Rows and Columns: (101, 4)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        101 non-null    int64
 1   Category  101 non-null    object
 2   Question  101 non-null    object
 3   Answer    101 non-null    object
dtypes: int64(1), object(3)
memory usage: 3.3+ KB

In [16]:
print(df.columns)

Index(['ID', 'Category', 'Question', 'Answer'], dtype='object')

In [17]:
print(df.dtypes)

ID           int64
Category    object
Question    object
Answer      object
dtype: object

In [18]:
print(df.isnull().sum())

ID          0
Category    0
Question    0
Answer      0
dtype: int64

In [19]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [20]:
df = df.drop_duplicates()

In [21]:
print(df["Category"].unique())

['Greeting' 'Admission' 'Courses' 'Library' 'Hostel' 'Placement' 'Fees'
 'Faculty' 'Examination' 'Campus']

In [22]:
print(df["Category"].value_counts())

Category
Library        13
Admission      11
Greeting       10
Placement      10
Faculty        10
Fees           10
Examination    10
Courses         9
Hostel          9
Campus          9
Name: count, dtype: int64

In [23]:
print(df["Question"].nunique())

100

In [24]:
print(df["Answer"].nunique())

98

In [25]:
print(df[df["Question"]==""])

Empty DataFrame
Columns: [ID, Category, Question, Answer]
Index: []

In [26]:
print(df[df["Answer"]==""])

Empty DataFrame
Columns: [ID, Category, Question, Answer]
Index: []

In [27]:
df["Question"] = df["Question"].str.lower()

In [28]:
df["Question"] = df["Question"].str.strip()
df["Answer"] = df["Answer"].str.strip()

In [29]:
df["Answer_Length"] = df["Answer"].apply(len)
df[["Answer","Answer_Length"]].head()

                                         Answer  Answer_Length
0  Hello! Welcome to the College Query Chatbot.             44
1                 Hi! How can I help you today?             29
2         Good Morning! Welcome to our college.             37
3           Good Evening! How can I assist you?             35
4                   Thank you! Have a nice day.             27

In [30]:
df.sample(5)

,ID,Category,Question,Answer,Answer_Length
83,87,Examination,hall ticket,Hall tickets can be downloaded from the portal.,47
95,100,Campus,college timings,College working hours are from 9:00 AM to 4:30...,50
55,59,Placement,resume building,Resume preparation sessions are organized.,42
62,66,Fees,late fee,Late fee may be applicable after the due date.,46
57,61,Fees,fee structure,Please contact the Accounts Office for fee det...,51

In [31]:
df.to_csv("../cleaned_dataset/cleaned_college_faq.csv", index=False)

In [32]:
clean_df = pd.read_csv("../cleaned_dataset/cleaned_college_faq.csv")
clean_df.head()

,ID,Category,Question,Answer,Answer_Length
0,1,Greeting,hi,Hello! Welcome to the College Query Chatbot.,44
1,2,Greeting,hello,Hi! How can I help you today?,29
2,3,Greeting,good morning,Good Morning! Welcome to our college.,37
3,4,Greeting,good evening,Good Evening! How can I assist you?,35
4,5,Greeting,bye,Thank you! Have a nice day.,27

In [33]:
print(clean_df.shape)

(101, 5)